name: "Setup Python and Install Deps"
description: "Configures Python and installs dependencies"
inputs:
  python-version:
    description: "Python version to install"
    required: true
  extra-packages:
    description: "Optional extra packages"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install requirements
      run: |
        echo "requests==2.32.0" > requirements.txt
        pip install -r requirements.txt ${{ inputs.extra-packages }}
      shell: bash
